# Generated by Django 4.1.3 on 2022-12-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenuePredict', '0003_testtaskdb_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaskdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
