# Generated by Django 4.1.3 on 2022-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenuePredict', '0004_alter_testtaskdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaskdb',
            name='CityGroup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='OpenDate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='P7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaskdb',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
