# Generated by Django 4.1.3 on 2022-12-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevenuePredict', '0005_alter_testtaskdb_citygroup_alter_testtaskdb_opendate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtaskdb',
            name='revenue',
        ),
    ]
